name: Fetch Matches List

on:
  workflow_dispatch:
  # schedule:
  #   # 07:00 VN hằng ngày = UTC 00:00
  #   - cron: "0 0 * * *"

jobs:
  fetch-matches-list:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run fetch matches list
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: npm run fetch-matches-list
